// inspector/src/AssessmentMap.tsx
import { Fragment, useState, type CSSProperties } from 'react';
import type { InvocationView } from '../../src/inspector/view.js';
import { Button } from '../../web/components/ui/button.js';
import DecisionIcon from './DecisionIcon.js';
import ConfidenceMeter from './ConfidenceMeter.js';
import { actionPreview, decisionLabel, gateTone, contributionExplanation, toolLabel, type RuleView } from './presentation.js';
import { mapChecks, checkIcon, checkPosition, incomingPath, outgoingPath, type MapCheck } from './decision-map.js';

export default function AssessmentMap({ view, rule, inspect }: { view: InvocationView; rule: RuleView | undefined; inspect: (check: string) => void }) {
  const [active, setActive] = useState(''), [motion, setMotion] = useState(0);
  const preview = actionPreview(view), checks = mapChecks(rule);
  const outgoingTone = (check: MapCheck) => check.gate && rule ? gateTone(rule, check.gate) : '';
  const choose = (check: MapCheck) => { setActive(check.id); setMotion(value => value + 1); inspect(check.label); };
  return <div className="map-stage" style={{ '--check-count': checks.length } as CSSProperties}>
    <div className={`decision-map ${motion % 2 === 1 ? 'trace-a' : motion > 0 ? 'trace-b' : ''}`} role="group" aria-label="Decision map">
      <svg className="map-connections" viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-hidden="true">
        {checks.map((check, index) => <Fragment key={check.id}>
          <path className={check.unknown ? 'unrecorded' : ''} pathLength="1" d={incomingPath(checkPosition(index, checks.length))} />
          <path className={`map-edge ${outgoingTone(check)} ${check.unknown ? 'unrecorded' : ''} ${active === check.id ? 'is-selected' : ''}`} pathLength="1" d={outgoingPath(checkPosition(index, checks.length))} />
        </Fragment>)}
      </svg>
      <div className="map-action map-endpoint">
        <span className="map-symbol filled"><DecisionIcon kind={view.identity?.toolName === 'bash' ? 'action' : ['read', 'write', 'edit'].includes(view.identity?.toolName ?? '') ? 'document' : 'tool'} /></span>
        <h3>{toolLabel(view.identity?.toolName ?? 'Unknown tool')}</h3>
        {preview ? <pre className="action-preview" aria-label="Recorded action"><code>{preview}</code></pre> : <p className="action-unavailable">Command or file path not recorded. Submitted arguments remain in evidence.</p>}
      </div>
      <div className="map-checks">{checks.map((check, index) =>
        <div key={check.id} className={`map-check ${outgoingTone(check)}`} style={{ '--node-y': `${checkPosition(index, checks.length)}%` } as CSSProperties}>
          <Button variant="outline" className="map-symbol" aria-label={`Inspect ${check.label.toLowerCase()}`} aria-controls="selected-check-details" aria-pressed={active === check.id} onClick={() => choose(check)}><DecisionIcon kind={checkIcon(check)} /></Button>
          <div className="map-caption">
            <h3>{check.label} <span>/ {check.value}</span></h3>
            {check.id === 'outcome' && rule && <>
              <p className="map-rule-text" title={rule.text}>{rule.text}</p>
              <p className="map-rule-location">{rule.builtin ? 'Built-in integrity' : `Rule at line ${rule.line ?? 'unavailable'}`} · Severity {rule.enforcement}</p>
              {rule.evidenceGate === 'not-applicable' && <p className="map-check-note">Evidence-confidence gate does not apply. No evidence score.</p>}
            </>}
            {check.reading && <ConfidenceMeter {...check.reading} />}
            {check.gate && rule && <p className="map-check-note">{contributionExplanation(rule, view.identity?.mode)}</p>}
            {check.unknown && <p className="map-check-note">Unknown does not mean passed.</p>}
          </div>
        </div>)}</div>
      <div className="map-policy map-endpoint">
        <span className="map-symbol filled"><DecisionIcon kind="policy" /></span>
        <h3>Recorded assessment</h3><p className="map-verdict">{decisionLabel(view.decision, view.identity?.mode)}</p>
      </div>
    </div>
  </div>;
}

// inspector/src/AssessmentMap.svelte
<script lang="ts">
  import type { InvocationView } from '../../src/inspector/view';
  import DecisionIcon from './DecisionIcon.svelte';
  import ConfidenceMeter from './ConfidenceMeter.svelte';
  import { actionPreview, decisionLabel, gateTone, contributionExplanation, toolLabel, type RuleView } from './presentation';
  import { mapChecks, checkIcon, checkPosition, incomingPath, outgoingPath, type MapCheck } from './decision-map';
  export let view: InvocationView;
  export let rule: RuleView | undefined;
  export let inspect: (check: string) => void;
  let active = '', motion = 0;
  $: preview = actionPreview(view);
  $: checks = mapChecks(rule);
  const outgoingTone = (check: MapCheck) => check.gate && rule ? gateTone(rule, check.gate) : '';
  function choose(check: MapCheck) { active = check.id; motion++; inspect(check.label); }
</script>
  <div class="map-stage" style:--check-count={checks.length}>
    <div class="decision-map" role="group" aria-label="Decision map" class:trace-a={motion % 2 === 1} class:trace-b={motion > 0 && motion % 2 === 0}>
      <svg class="map-connections" viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-hidden="true">
        {#each checks as check, index (check.id)}
          <path class:unrecorded={check.unknown} pathLength="1" d={incomingPath(checkPosition(index, checks.length))} />
          <path class={`map-edge ${outgoingTone(check)}`} class:unrecorded={check.unknown} class:is-selected={active === check.id} pathLength="1" d={outgoingPath(checkPosition(index, checks.length))} />
        {/each}
      </svg>
      <div class="map-action map-endpoint">
        <span class="map-symbol filled"><DecisionIcon kind={view.identity?.toolName === 'bash' ? 'action' : ['read', 'write', 'edit'].includes(view.identity?.toolName ?? '') ? 'document' : 'tool'} /></span>
        <h3>{toolLabel(view.identity?.toolName ?? 'Unknown tool')}</h3>
        {#if preview}<pre class="action-preview" aria-label="Recorded action"><code>{preview}</code></pre>
        {:else}<p class="action-unavailable">Command or file path not recorded. Submitted arguments remain in evidence.</p>{/if}
      </div>
      <div class="map-checks">
        {#each checks as check, index (check.id)}
          <div class={`map-check ${outgoingTone(check)}`} style:--node-y={`${checkPosition(index, checks.length)}%`}>
            <button class="map-symbol" aria-label={`Inspect ${check.label.toLowerCase()}`} aria-controls="selected-check-details" aria-pressed={active === check.id} on:click={() => choose(check)}>
              <DecisionIcon kind={checkIcon(check)} />
            </button>
            <div class="map-caption">
              <h3>{check.label} <span>/ {check.value}</span></h3>
              {#if check.id === 'outcome' && rule}
                <p class="map-rule-text" title={rule.text}>{rule.text}</p>
                <p class="map-rule-location">{rule.builtin ? 'Built-in integrity' : `Rule at line ${rule.line ?? 'unavailable'}`} · Severity {rule.enforcement}</p>
                {#if rule.evidenceGate === 'not-applicable'}<p class="map-check-note">Evidence-confidence gate does not apply. No evidence score.</p>{/if}
              {/if}
              {#if check.reading}<ConfidenceMeter {...check.reading} />{/if}
              {#if check.gate && rule}<p class="map-check-note">{contributionExplanation(rule, view.identity?.mode)}</p>{/if}
              {#if check.unknown}<p class="map-check-note">Unknown does not mean passed.</p>{/if}
            </div>
          </div>
        {/each}
      </div>
      <div class="map-policy map-endpoint">
        <span class="map-symbol filled"><DecisionIcon kind="policy" /></span>
        <h3>Recorded assessment</h3>
        <p class="map-verdict">{decisionLabel(view.decision, view.identity?.mode)}</p>
      </div>
    </div>
  </div>
