// inspector/src/QuestionView.tsx
import SafeMarkdown from './SafeMarkdown.js';
import StatusChip from './StatusChip.js';
import { pretty } from './presentation.js';

const object = (value: unknown): Record<string, unknown> => value !== null && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};

export default function QuestionView({ question, format = 'rich' }: { question: unknown; format?: 'rich' | 'json' }) {
  const data = object(question), choices = Object.entries(object(data.criteria));
  const other = Object.fromEntries(Object.entries(data).filter(([key]) => !['instructions', 'criteria'].includes(key)));
  if (format === 'json' || typeof data.instructions !== 'string') return <pre className="question-json">{pretty(question)}</pre>;
  return <div className="question-rich">
    <div className="rich-markdown"><SafeMarkdown source={data.instructions} /></div>
    {choices.length ? <><h6>Answer choices</h6><dl className="answer-choices">{choices.map(([label, description]) =>
      <div key={label}><dt><StatusChip value={label} /></dt><dd>{typeof description === 'string' ? <div className="rich-markdown"><SafeMarkdown source={description} /></div> : <pre>{pretty(description)}</pre>}</dd></div>)}</dl></>
      : <p className="muted">No answer choices recorded.</p>}
    {!!Object.keys(other).length && <details className="question-metadata"><summary>Other recorded fields</summary><pre>{pretty(other)}</pre></details>}
    {data.criteria !== undefined && (!choices.length || typeof data.criteria !== 'object') && <pre>{pretty(data.criteria)}</pre>}
  </div>;
}

// inspector/src/QuestionView.svelte
<script lang="ts">
  import SafeMarkdown from './SafeMarkdown.svelte';
  import StatusChip from './StatusChip.svelte';
  import { pretty } from './presentation';
  export let question: unknown;
  export let format: 'rich' | 'json' = 'rich';
  const object = (value: unknown): Record<string, unknown> => value !== null && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
  $: data = object(question);
  $: choices = Object.entries(object(data.criteria));
  $: other = Object.fromEntries(Object.entries(data).filter(([key]) => !['instructions', 'criteria'].includes(key)));
</script>

{#if format === 'json'}<pre class="question-json">{pretty(question)}</pre>
{:else if typeof data.instructions === 'string'}
  <div class="question-rich">
    <div class="rich-markdown"><SafeMarkdown source={data.instructions} /></div>
    {#if choices.length}
      <h6>Answer choices</h6>
      <dl class="answer-choices">{#each choices as [label, description]}<div><dt><StatusChip value={label} /></dt><dd>{#if typeof description === 'string'}<div class="rich-markdown"><SafeMarkdown source={description} /></div>{:else}<pre>{pretty(description)}</pre>{/if}</dd></div>{/each}</dl>
    {:else}<p class="muted">No answer choices recorded.</p>{/if}
    {#if Object.keys(other).length}<details class="question-metadata"><summary>Other recorded fields</summary><pre>{pretty(other)}</pre></details>{/if}
    {#if data.criteria !== undefined && (!choices.length || typeof data.criteria !== 'object')}<pre>{pretty(data.criteria)}</pre>{/if}
  </div>
{:else}<pre class="question-json">{pretty(question)}</pre>{/if}
