// inspector/src/RuleDetail.svelte
<script lang="ts">
  import { gateLabels, gateExplanation, gateTone, contributionExplanation, confidenceReadings, type RuleView } from './presentation';
  import ConfidenceMeter from './ConfidenceMeter.svelte';
  import StatusChip from './StatusChip.svelte';
  export let rule: RuleView;
  export let mode: string | undefined = undefined;
</script>

<!-- svelte-ignore a11y_no_noninteractive_tabindex (Scrollable assessment region needs keyboard access.) -->
<section aria-label="Selected rule" class="rule-detail" tabindex="0">
  <div class="rule-detail-title"><h3>{rule.builtin ? 'Built-in integrity' : `Rule at line ${rule.line}`}</h3><span class="setting">{rule.enforcement}</span></div>
  <p class="snapshot-text">{rule.text}</p>
  {#if rule.result?.outcome}<p class="rule-outcome">Rule outcome <StatusChip value={rule.result.outcome.choice ?? 'Unavailable'} /></p>{/if}
  {#if rule.evidenceGate === 'not-applicable'}<p class="muted">Evidence-confidence gate does not apply. No evidence score was recorded.</p>{/if}
  {#if rule.gateIds?.length || rule.contribution.includes('approval')}<p class="contribution">{contributionExplanation(rule, mode)}</p>{/if}
  {#if rule.gateIds === null}<p class="missing-data">Gate coverage unavailable: not recorded.</p>
  {:else if !rule.gateIds.length}<p class="muted">No gates recorded.</p>
  {:else}<ul class="gate-list">{#each rule.gateIds as gate}{#if !confidenceReadings(rule).some(r => r.gate === gate)}<li><StatusChip value={gate} label={gateLabels[gate] ?? 'Unrecognized recorded gate'} tone={gateTone(rule, gate)} /><p>{gateExplanation(gate, rule)}</p></li>{/if}{/each}</ul>
  {/if}
  {#each confidenceReadings(rule) as reading}<ConfidenceMeter label={reading.label} value={reading.value} threshold={reading.threshold} />{/each}
  {#if rule.result?.outcome?.choice === 'PASS' && rule.gateIds?.some(g => g.includes('confidence') || g === 'evidence-insufficient')}
    <p class="confidence-note">PASS was selected for the rule outcome, but a confidence or evidence check did not pass. This is not a reported violation.</p>
  {/if}
  <details class="rule-technical disclosure"><summary>Probabilities and rule details</summary>
  <p class="contribution">{contributionExplanation(rule, mode)}</p>
  <p class="setting">Enforcement: {rule.enforcement}</p>
  {#if rule.gateIds?.length}<details class="gate-details"><summary>Gate identifiers</summary><ul>{#each rule.gateIds as gate}<li><code>{gate}</code></li>{/each}</ul></details>{/if}
  <div class="distributions">
    {#each ['outcome', 'evidence'] as kind}
      <table>
        <caption>{kind === 'outcome' ? 'Outcome' : 'Evidence sufficiency'}</caption>
        <thead><tr><th scope="col">Label</th><th scope="col">Probability</th></tr></thead>
        <tbody>
          {#each Object.entries(rule.result?.[kind]?.probabilities ?? {}) as [label, probability]}
            <tr class:selected-label={label === rule.result?.[kind]?.choice}><th scope="row">{#if label === rule.result?.[kind]?.choice}<StatusChip value={label} /><small>selected</small>{:else}{label}{/if}</th><td>{String(probability)}</td></tr>
          {:else}<tr><td colspan="2">{kind === 'evidence' && rule.evidenceGate === 'not-applicable' ? 'Not applicable. No evidence score.' : 'Assessment unavailable.'}</td></tr>{/each}
        </tbody>
        <tfoot><tr><th scope="row">{kind === 'outcome' ? 'Selected outcome threshold' : 'SUFFICIENT threshold'}</th><td>{kind === 'outcome' ? rule.thresholds.effectThreshold ?? 'Not recorded' : rule.evidenceGate === 'not-applicable' ? 'Not applicable' : rule.thresholds.evidenceThreshold ?? 'Not recorded'}</td></tr></tfoot>
      </table>
    {/each}
  </div>
  <p class="muted probability-note">Model probabilities, not calibrated safety guarantees. No hidden model reasoning is recorded.</p>
  </details>
</section>

// inspector/src/RuleDetail.tsx
import { gateLabels, gateExplanation, gateTone, contributionExplanation, confidenceReadings, type RuleView } from './presentation.js';
import ConfidenceMeter from './ConfidenceMeter.js';
import StatusChip from './StatusChip.js';

export default function RuleDetail({ rule, mode }: { rule: RuleView; mode?: string }) {
  const readings = confidenceReadings(rule);
  return <section aria-label="Selected rule" className="rule-detail" tabIndex={0}>
    <div className="rule-detail-title"><h3>{rule.builtin ? 'Built-in integrity' : `Rule at line ${rule.line}`}</h3><span className="setting">{rule.enforcement}</span></div>
    {!rule.builtin && <p className="setting">Source role: {rule.origin?.role ?? 'unknown, not recorded'}{rule.origin?.source && ` | ${rule.origin.source}`}</p>}
    <p className="snapshot-text">{rule.text}</p>
    {rule.result?.outcome && <p className="rule-outcome">Rule outcome <StatusChip value={rule.result.outcome.choice ?? 'Unavailable'} /></p>}
    {rule.evidenceGate === 'not-applicable' && <p className="muted">Evidence-confidence gate does not apply. No evidence score was recorded.</p>}
    {(!!rule.gateIds?.length || rule.contribution.includes('approval')) && <p className="contribution">{contributionExplanation(rule, mode)}</p>}
    {rule.gateIds === null ? <p className="missing-data">Gate coverage unavailable: not recorded.</p>
      : !rule.gateIds.length ? <p className="muted">No gates recorded.</p>
      : <ul className="gate-list">{rule.gateIds.filter(gate => !readings.some(r => r.gate === gate)).map(gate => <li key={gate}><StatusChip value={gate} label={gateLabels[gate] ?? 'Unrecognized recorded gate'} tone={gateTone(rule, gate)} /><p>{gateExplanation(gate, rule)}</p></li>)}</ul>}
    {readings.map(reading => <ConfidenceMeter key={reading.gate} label={reading.label} value={reading.value} threshold={reading.threshold} />)}
    {rule.result?.outcome?.choice === 'PASS' && rule.gateIds?.some(g => g.includes('confidence') || g === 'evidence-insufficient') && <p className="confidence-note">PASS was selected for the rule outcome, but a confidence or evidence check did not pass. This is not a reported violation.</p>}
    <details className="rule-technical disclosure"><summary>Probabilities and rule details</summary>
      <p className="contribution">{contributionExplanation(rule, mode)}</p>
      <p className="setting">Enforcement: {rule.enforcement}</p>
      {rule.origin && <p className="setting">Recorded target: {rule.origin.target ?? 'not recorded'}<br />Source SHA-256: {rule.origin.digest ?? 'not recorded'}</p>}
      {!!rule.gateIds?.length && <details className="gate-details"><summary>Gate identifiers</summary><ul>{rule.gateIds.map(gate => <li key={gate}><code>{gate}</code></li>)}</ul></details>}
      <div className="distributions">{(['outcome', 'evidence'] as const).map(kind => {
        const entries = Object.entries(rule.result?.[kind]?.probabilities ?? {});
        return <table key={kind}>
          <caption>{kind === 'outcome' ? 'Outcome' : 'Evidence sufficiency'}</caption>
          <thead><tr><th scope="col">Label</th><th scope="col">Probability</th></tr></thead>
          <tbody>{entries.length ? entries.map(([label, probability]) => <tr key={label} className={label === rule.result?.[kind]?.choice ? 'selected-label' : ''}>
            <th scope="row">{label === rule.result?.[kind]?.choice ? <><StatusChip value={label} /><small>selected</small></> : label}</th><td>{String(probability)}</td>
          </tr>) : <tr><td colSpan={2}>{kind === 'evidence' && rule.evidenceGate === 'not-applicable' ? 'Not applicable. No evidence score.' : 'Assessment unavailable.'}</td></tr>}</tbody>
          <tfoot><tr><th scope="row">{kind === 'outcome' ? 'Selected outcome threshold' : 'SUFFICIENT threshold'}</th><td>{kind === 'outcome' ? rule.thresholds.effectThreshold ?? 'Not recorded' : rule.evidenceGate === 'not-applicable' ? 'Not applicable' : rule.thresholds.evidenceThreshold ?? 'Not recorded'}</td></tr></tfoot>
        </table>;
      })}</div>
      <p className="muted probability-note">Model probabilities, not calibrated safety guarantees. No hidden model reasoning is recorded.</p>
    </details>
  </section>;
}
