// inspector/src/SafeMarkdown.tsx
import { createElement, Fragment } from 'react';
import { Lexer, type Token } from 'marked';

export default function SafeMarkdown({ source = '', tokens }: { source?: string; tokens?: Token[] }) {
  const content = tokens ?? Lexer.lex(source, { gfm: true, breaks: true });
  return <>{content.filter(token => token.type !== 'space').map((token, index) => {
    let node;
    switch (token.type) {
      case 'heading': node = createElement(`h${Math.min(6, Math.max(4, token.depth + 3))}`, null, <SafeMarkdown tokens={token.tokens} />); break;
      case 'paragraph': node = <p><SafeMarkdown tokens={token.tokens} /></p>; break;
      case 'escape': node = token.text; break;
      case 'text': node = token.tokens ? <SafeMarkdown tokens={token.tokens} /> : token.text; break;
      case 'strong': node = <strong><SafeMarkdown tokens={token.tokens} /></strong>; break;
      case 'em': node = <em><SafeMarkdown tokens={token.tokens} /></em>; break;
      case 'del': node = <del><SafeMarkdown tokens={token.tokens} /></del>; break;
      case 'codespan': node = <code>{token.text}</code>; break;
      case 'code': node = <pre><code>{token.text}</code></pre>; break;
      case 'br': node = <br />; break;
      case 'hr': node = <hr />; break;
      case 'blockquote': node = <blockquote><SafeMarkdown tokens={token.tokens} /></blockquote>; break;
      case 'list': {
        const items = token.items.map((item: { task?: boolean; checked?: boolean; tokens: Token[] }, i: number) =>
          <li key={i}>{item.task && (item.checked ? '[x] ' : '[ ] ')}<SafeMarkdown tokens={item.tokens} /></li>);
        node = token.ordered ? <ol start={typeof token.start === 'number' ? token.start : 1}>{items}</ol> : <ul>{items}</ul>;
        break;
      }
      case 'table': node = <table><thead><tr>{token.header.map((cell: { tokens: Token[] }, i: number) => <th key={i} scope="col"><SafeMarkdown tokens={cell.tokens} /></th>)}</tr></thead>
        <tbody>{token.rows.map((row: { tokens: Token[] }[], i: number) => <tr key={i}>{row.map((cell, j) => <td key={j}><SafeMarkdown tokens={cell.tokens} /></td>)}</tr>)}</tbody></table>; break;
      case 'link': node = <span className="inert-link"><SafeMarkdown tokens={token.tokens} /> <code>({token.href})</code></span>; break;
      case 'html': node = token.block ? <pre className="markdown-literal"><code>{token.raw}</code></pre> : <code>{token.raw}</code>; break;
      default: node = token.raw;
    }
    return <Fragment key={index}>{node}</Fragment>;
  })}</>;
}

// inspector/src/SafeMarkdown.svelte
<script lang="ts">
  import { Lexer, type Token } from 'marked';
  export let source = '';
  export let tokens: Token[] | undefined = undefined;
  $: content = tokens ?? Lexer.lex(source, { gfm: true, breaks: true });
</script>

{#each content.filter(token => token.type !== 'space') as token}
  {#if token.type === 'heading'}
    <svelte:element this={`h${Math.min(6, Math.max(4, token.depth + 3))}`}><svelte:self tokens={token.tokens} /></svelte:element>
  {:else if token.type === 'paragraph'}
    <p><svelte:self tokens={token.tokens} /></p>
  {:else if token.type === 'escape'}{token.text}
  {:else if token.type === 'text'}
    {#if token.tokens}<svelte:self tokens={token.tokens} />{:else}{token.text}{/if}
  {:else if token.type === 'strong'}<strong><svelte:self tokens={token.tokens} /></strong>
  {:else if token.type === 'em'}<em><svelte:self tokens={token.tokens} /></em>
  {:else if token.type === 'del'}<del><svelte:self tokens={token.tokens} /></del>
  {:else if token.type === 'codespan'}<code>{token.text}</code>
  {:else if token.type === 'code'}<pre><code>{token.text}</code></pre>
  {:else if token.type === 'br'}<br />
  {:else if token.type === 'hr'}<hr />
  {:else if token.type === 'blockquote'}<blockquote><svelte:self tokens={token.tokens} /></blockquote>
  {:else if token.type === 'list'}
    {#if token.ordered}<ol start={typeof token.start === 'number' ? token.start : 1}>{#each token.items as item}<li>{#if item.task}{item.checked ? '[x] ' : '[ ] '}{/if}<svelte:self tokens={item.tokens} /></li>{/each}</ol>
    {:else}<ul>{#each token.items as item}<li>{#if item.task}{item.checked ? '[x] ' : '[ ] '}{/if}<svelte:self tokens={item.tokens} /></li>{/each}</ul>{/if}
  {:else if token.type === 'table'}
    <table><thead><tr>{#each token.header as cell}<th scope="col"><svelte:self tokens={cell.tokens} /></th>{/each}</tr></thead><tbody>{#each token.rows as row}<tr>{#each row as cell}<td><svelte:self tokens={cell.tokens} /></td>{/each}</tr>{/each}</tbody></table>
  {:else if token.type === 'link'}
    <span class="inert-link"><svelte:self tokens={token.tokens} /> <code>({token.href})</code></span>
  {:else if token.type === 'html'}
    {#if token.block}<pre class="markdown-literal"><code>{token.raw}</code></pre>{:else}<code>{token.raw}</code>{/if}
  {:else}
    {token.raw}
  {/if}
{/each}
